apiVersion: batch/v1
kind: CronJob
metadata:
  name: billing
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: billing
              image: saas
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
